### ISSUE TITLE
Major tag v1 is not updated

### ISSUE THREAD

**Issue by gofrolist** [accurics/terrascan-action#25]
Major tag v12 is not updated and pointed to very old commit https://github.com/bridgecrewio/checkov-action/commits/v12

Regarding to official GitHub [recommendations](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations) and [here](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management)

> Make the new release available to those binding to the major version tag: Move the major version tag (v1, v2, etc.) to point to the ref of the current release. This will act as the stable release for that major version. You should keep this tag updated to the most recent stable minor/patch release.

Because of that I can't use v1 tag and should point it to specific tag like v1.3.0
```
    - name: Run Terrascan
      id: terrascan
      uses: accurics/terrascan-action@v1.3.0
```
Only way I can see it right now is use main branch which is not good for production usage
```
    - name: Run Terrascan
      id: terrascan
      uses: accurics/terrascan-action@main
```

You can use other GitHub actions like [actions-tagger](https://github.com/marketplace/actions/actions-tagger) or [update-major-minor-semver](https://github.com/marketplace/actions/update-major-minor-semver) for this purpose.

**Comment by cesar-rodriguez** [comment]
@gofrolist thanks for opening the issue! I wasn't aware of the expected GitHub behavior for versioning. I opened #28 using one of your suggestions and hopefully, this will address the issue on our next release (in a few days).
